version: "3.9"

services:
  photobooth:
    build: .
    # privileged: true
    devices:
      - '/dev/bus/usb/005:/dev/bus/usb/005'
    volumes:
      - ./:/app
      - /app/resources/css/
      - /app/resources/js/
      - /app/vendor/
    ports:
      - "8080:80"
